name: TryHackMe Update Badge

on:
  schedule:
    - cron: '0 0 * * *' # Runs every 24 hours
  workflow_dispatch:

jobs:
  tryhackme-badge-update:
    name: Update TryHackMe badge image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: p4p1/tryhackme-badge-workflow@main
        with:
          username: "VirusDanny"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
